In [6]:
import pandas as pd

In [1]:
import json

f = open('orders_etl.json')
data = json.load(f)

In [2]:
data

[{'order_id': 1,
  'order_date': '2024-01-10',
  'total_amount': 200.5,
  'customer': {'customer_id': 101,
   'name': 'John Doe',
   'email': 'johndoe@example.com',
   'address': '123 Main StSpringfield'},
  'products': [{'product_id': 'P01',
    'name': 'Wireless Mouse',
    'category': 'Electronics',
    'price': 25.0,
    'quantity': 2},
   {'product_id': 'P02',
    'name': 'Bluetooth Keyboard',
    'category': 'Electronics',
    'price': 45.0,
    'quantity': 1}]},
 {'order_id': 2,
  'order_date': '2024-01-12',
  'total_amount': 150.0,
  'customer': {'customer_id': 102,
   'name': 'Jane Smith',
   'email': 'janesmith@example.com',
   'address': '456 Oak StSpringfield'},
  'products': [{'product_id': 'P03',
    'name': 'Laptop Stand',
    'category': 'Electronics',
    'price': 75.0,
    'quantity': 1}]},
 {'order_id': 3,
  'order_date': '2024-01-12',
  'total_amount': 120.0,
  'customer': {'customer_id': 103,
   'name': 'Alice Johnson',
   'email': 'alicejohnson@example.com',
   'address': '789 Birch StSpringfield'},
  'products': [{'product_id': 'P04',
    'name': 'Gaming Headset',
    'category': 'Electronics',
    'price': 60.0,
    'quantity': 2}]},
 {'order_id': 4,
  'order_date': '2024-01-13',
  'total_amount': 300.5,
  'customer': {'customer_id': 101,
   'name': 'John Doe',
   'email': 'johndoe@example.com',
   'address': '123 Main StSpringfield'},
  'products': [{'product_id': 'P01',
    'name': 'Wireless Mouse',
    'category': 'Electronics',
    'price': 25.0,
    'quantity': 3},
   {'product_id': 'P02',
    'name': 'Bluetooth Keyboard',
    'category': 'Electronics',
    'price': 45.0,
    'quantity': 2}]},
 {'order_id': 5,
  'order_date': '2024-01-14',
  'total_amount': 180.0,
  'customer': {'customer_id': 104,
   'name': 'Bob Brown',
   'email': 'bobbrown@example.com',
   'address': '101 Maple StSpringfield'},
  'products': [{'product_id': 'P03',
    'name': 'Laptop Stand',
    'category': 'Electronics',
    'price': 75.0,
    'quantity': 1},
   {'product_id': 'P04',
    'name': 'Gaming Headset',
    'category': 'Electronics',
    'price': 60.0,
    'quantity': 1}]},
 {'order_id': 6,
  'order_date': '2024-01-14',
  'total_amount': 250.0,
  'customer': {'customer_id': 105,
   'name': 'Sania',
   'email': 'sania@example.com',
   'address': '102 Pine StSpringfield'},
  'products': [{'product_id': 'P01',
    'name': 'Wireless Mouse',
    'category': 'Electronics',
    'price': 25.0,
    'quantity': 2},
   {'product_id': 'P02',
    'name': 'Bluetooth Keyboard',
    'category': 'Electronics',
    'price': 45.0,
    'quantity': 2},
   {'product_id': 'P04',
    'name': 'Gaming Headset',
    'category': 'Electronics',
    'price': 60.0,
    'quantity': 1}]},
 {'order_id': 7,
  'order_date': '2024-01-16',
  'total_amount': 180.0,
  'customer': {'customer_id': 106,
   'name': 'Rohit',
   'email': 'rohit@example.com',
   'address': '103 Cedar StSpringfield'},
  'products': [{'product_id': 'P02',
    'name': 'Bluetooth Keyboard',
    'category': 'Electronics',
    'price': 45.0,
    'quantity': 2},
   {'product_id': 'P05',
    'name': 'Desk Organizer',
    'category': 'Furniture',
    'price': 30.0,
    'quantity': 1}]},
 {'order_id': 8,
  'order_date': '2024-01-16',
  'total_amount': 230.0,
  'customer': {'customer_id': 107,
   'name': 'Nina Patel',
   'email': 'ninapatel@example.com',
   'address': '104 Birch StSpringfield'},
  'products': [{'product_id': 'P01',
    'name': 'Wireless Mouse',
    'category': 'Electronics',
    'price': 25.0,
    'quantity': 3},
   {'product_id': 'P03',
    'name': 'Laptop Stand',
    'category': 'Electronics',
    'price': 75.0,
    'quantity': 1}]},
 {'order_id': 9,
  'order_date': '2024-01-17',
  'total_amount': 310.0,
  'customer': {'customer_id': 108,
   'name': 'Tom Harris',
   'email': 'tomharris@example.com',
   'address': '105 Oak StSpringfield'},
  'products': [{'product_id': 'P04',
    'name': 'Gaming Headset',
    'category': 'Electronics',
    'price': 60.0,
    'quantity': 2},
   {'product_id': 'P02',
    'name': 'Bluetooth Keyboard',
    'category': 'Electronics',
    'price': 45.0,
    'quantity': 2}]},
 {'order_id': 10,
  'order_date': '2024-01-18',
  'total_amount': 130.0,
  'customer': {'customer_id': 109,
   'name': 'Eva Lee',
   'email': 'evalee@example.com',
   'address': '106 Elm StSpringfield'},
  'products': [{'product_id': 'P05',
    'name': 'Desk Organizer',
    'category': 'Furniture',
    'price': 30.0,
    'quantity': 1},
   {'product_id': 'P03',
    'name': 'Laptop Stand',
    'category': 'Electronics',
    'price': 75.0,
    'quantity': 1}]},
 {'order_id': 11,
  'order_date': '2024-01-18',
  'total_amount': 250.0,
  'customer': {'customer_id': 101,
   'name': 'John Doe',
   'email': 'johndoe@example.com',
   'address': '123 Main StSpringfield'},
  'products': [{'product_id': 'P04',
    'name': 'Gaming Headset',
    'category': 'Electronics',
    'price': 60.0,
    'quantity': 2},
   {'product_id': 'P02',
    'name': 'Bluetooth Keyboard',
    'category': 'Electronics',
    'price': 45.0,
    'quantity': 2}]},
 {'order_id': 12,
  'order_date': '2024-01-19',
  'total_amount': 180.0,
  'customer': {'customer_id': 103,
   'name': 'Alice Johnson',
   'email': 'alicejohnson@example.com',
   'address': '789 Birch StSpringfield'},
  'products': [{'product_id': 'P01',
    'name': 'Wireless Mouse',
    'category': 'Electronics',
    'price': 25.0,
    'quantity': 2},
   {'product_id': 'P05',
    'name': 'Desk Organizer',
    'category': 'Furniture',
    'price': 30.0,
    'quantity': 1}]}]

In [3]:
data[0] # 1st order

{'order_id': 1,
 'order_date': '2024-01-10',
 'total_amount': 200.5,
 'customer': {'customer_id': 101,
  'name': 'John Doe',
  'email': 'johndoe@example.com',
  'address': '123 Main StSpringfield'},
 'products': [{'product_id': 'P01',
   'name': 'Wireless Mouse',
   'category': 'Electronics',
   'price': 25.0,
   'quantity': 2},
  {'product_id': 'P02',
   'name': 'Bluetooth Keyboard',
   'category': 'Electronics',
   'price': 45.0,
   'quantity': 1}]}

In [4]:
# orders -> order_id, order_date, total_amount, quantity, customer_id, product_id
# products -> product_id, name, category, price
# customers -> customer_id, name, email, address

In [13]:
order_id = []
order_date = []
total_amount = []
quantity = []
customer_id = []
product_id = []
product_name = []
category = []
price = []
customer_name = []
email = []
address = []
cust_id = []

for order in data:
    cust_id.append(order['customer']['customer_id'])
    customer_name.append(order['customer']['name'])
    email.append(order['customer']['email'])
    address.append(order['customer']['address'])
    for product in order['products']:
        order_id.append(order['order_id'])
        order_date.append(order['order_date'])
        customer_id.append(order['customer']['customer_id'])
        total_amount.append(order['total_amount'])
        quantity.append(product['quantity'])
        product_id.append(product['product_id'])
        product_name.append(product['name'])
        category.append(product['category'])
        price.append(product['price'])

df_orders = pd.DataFrame ({
    'order_id':order_id,
    'order_date': order_date,
    'customer_id':customer_id,
    'total_amount': total_amount,
    'product_id': product_id,
    'quantity': quantity
})

df_products = pd.DataFrame ({
     'product_id': product_id,
     'product_name' : product_name,
     'category': category,
     'price' : price

})

df_customers = pd.DataFrame ({
     'customer_id': cust_id,
     'customer_name': customer_name,
     'email' : email,
     'address': address
})

df_customers.drop_duplicates(subset = 'customer_id', keep = 'last', inplace = True)


df_products.drop_duplicates(subset = 'product_id', keep = 'last', inplace = True)

df_orders

    order_id  order_date  customer_id  total_amount product_id  quantity
0          1  2024-01-10          101         200.5        P01         2
1          1  2024-01-10          101         200.5        P02         1
2          2  2024-01-12          102         150.0        P03         1
3          3  2024-01-12          103         120.0        P04         2
4          4  2024-01-13          101         300.5        P01         3
5          4  2024-01-13          101         300.5        P02         2
6          5  2024-01-14          104         180.0        P03         1
7          5  2024-01-14          104         180.0        P04         1
8          6  2024-01-14          105         250.0        P01         2
9          6  2024-01-14          105         250.0        P02         2
10         6  2024-01-14          105         250.0        P04         1
11         7  2024-01-16          106         180.0        P02         2
12         7  2024-01-16          106         180.0        P05         1
13         8  2024-01-16          107         230.0        P01         3
14         8  2024-01-16          107         230.0        P03         1
15         9  2024-01-17          108         310.0        P04         2
16         9  2024-01-17          108         310.0        P02         2
17        10  2024-01-18          109         130.0        P05         1
18        10  2024-01-18          109         130.0        P03         1
19        11  2024-01-18          101         250.0        P04         2
20        11  2024-01-18          101         250.0        P02         2
21        12  2024-01-19          103         180.0        P01         2
22        12  2024-01-19          103         180.0        P05         1

## Load Data into MySQL

In [ ]:
# pip install my-sql-connector-python sqlalchemy pandas mysql
# pip install pymysql

In [14]:
from sqlalchemy import create_engine, text 
engine = create_engine("mysql+pymysql://root:nadeem123@127.0.0.1:3306/sys")

In [15]:
df_orders.to_sql(name = 'orders', con = engine, index = False, if_exists = 'replace')

df_products.to_sql(name = 'products', con = engine, index = False, if_exists = 'replace')

df_customers.to_sql(name = 'customers', con = engine, index = False, if_exists = 'replace')

9